# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scrap.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'scrap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscrap.proto\"\x1f\n\x10ScrapearPeticion\x12\x0b\n\x03url\x18\x01 \x01(\t\"\"\n\x11ScrapearRespuesta\x12\r\n\x05\x64\x61tos\x18\x01 \x01(\t2L\n\x0fScrapearPaginas\x12\x39\n\x0eScrapearPagina\x12\x11.ScrapearPeticion\x1a\x12.ScrapearRespuesta\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scrap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRAPEARPETICION']._serialized_start=15
  _globals['_SCRAPEARPETICION']._serialized_end=46
  _globals['_SCRAPEARRESPUESTA']._serialized_start=48
  _globals['_SCRAPEARRESPUESTA']._serialized_end=82
  _globals['_SCRAPEARPAGINAS']._serialized_start=84
  _globals['_SCRAPEARPAGINAS']._serialized_end=160
# @@protoc_insertion_point(module_scope)
